<?php
require_once __DIR__ . '/../../backend/conexion.php';
if (session_status() === PHP_SESSION_NONE) session_start();
if (!isset($_SESSION['id_sesion'])) { header("Location: ../index.php"); exit(); }

$busqueda = $_GET['busqueda'] ?? '';
$filtro_activo = $_GET['activo'] ?? '';

$query = "SELECT * FROM aseguradoras WHERE 1=1";
$params = [];
if ($busqueda) { $query .= " AND (nombre ILIKE :busqueda OR codigo ILIKE :busqueda)"; $params[':busqueda'] = "%$busqueda%"; }
if ($filtro_activo !== '') { $query .= " AND activo = :activo"; $params[':activo'] = $filtro_activo === '1'; }
$query .= " ORDER BY nombre";
$aseguradoras = [];
try { $stmt = $conexion->prepare($query); $stmt->execute($params); $aseguradoras = $stmt->fetchAll(PDO::FETCH_ASSOC); } catch(PDOException $e) {}

$base_url = '/sistema-gestor-de-farmacias';
?>
<div class="dashboard-container">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2 class="text-primary"><span class="material-symbols-rounded align-middle me-2">health_and_safety</span>Aseguradoras</h2>
        <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalAseguradora" onclick="resetFormAseguradora()">+ Nueva Aseguradora</button>
    </div>
    <div class="card mb-3"><div class="card-body"><div class="row g-2"><div class="col-md-4"><input type="text" class="form-control" id="busqueda" placeholder="Buscar" value="<?php echo htmlspecialchars($busqueda); ?>"></div><div class="col-md-3"><select class="form-select" id="filtroActivo"><option value="">Todos</option><option value="1" <?php echo $filtro_activo==='1'?'selected':''; ?>>Activos</option><option value="0" <?php echo $filtro_activo==='0'?'selected':''; ?>>Inactivos</option></select></div><div class="col-md-5"><button class="btn btn-primary" onclick="aplicarFiltros()">Filtrar</button> <button class="btn btn-secondary" onclick="limpiarFiltros()">Limpiar</button></div></div></div></div>
    <div class="card"><div class="card-body p-0"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>Código</th><th>Nombre</th><th>RNC</th><th>Teléfono</th><th>Cobertura %</th><th>Activo</th><th>Acciones</th></tr></thead><tbody><?php foreach($aseguradoras as $a): ?><tr><td><?php echo htmlspecialchars($a['codigo']); ?></td><td><?php echo htmlspecialchars($a['nombre']); ?></td><td><?php echo htmlspecialchars($a['rnc']); ?></td><td><?php echo htmlspecialchars($a['telefono']); ?></td><td><?php echo $a['porcentaje_cobertura_default']; ?>%</td><td><?php echo $a['activo']?'<span class="badge bg-success">Activo</span>':'<span class="badge bg-secondary">Inactivo</span>'; ?></td><td><button class="btn btn-sm btn-outline-primary" onclick="editarAseguradora(<?php echo $a['id_aseguradora']; ?>)">Editar</button> <button class="btn btn-sm btn-outline-secondary" onclick="toggleEstadoAseguradora(<?php echo $a['id_aseguradora']; ?>, <?php echo $a['activo']?'false':'true'; ?>)"><?php echo $a['activo']?'Desactivar':'Activar'; ?></button></td></tr><?php endforeach; ?></tbody></table></div></div>
</div>
<div class="modal fade" id="modalAseguradora" tabindex="-1" data-bs-backdrop="false"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header bg-primary text-white"><h5 class="modal-title">Aseguradora</h5><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body"><form id="formAseguradora"><input type="hidden" id="id_aseguradora"><div class="row g-2"><div class="col-md-6"><label>Código *</label><input type="text" class="form-control" id="codigo" required></div><div class="col-md-6"><label>Nombre *</label><input type="text" class="form-control" id="nombre" required></div><div class="col-md-4"><label>RNC</label><input type="text" class="form-control" id="rnc"></div><div class="col-md-4"><label>Teléfono</label><input type="text" class="form-control" id="telefono"></div><div class="col-md-4"><label>Email</label><input type="email" class="form-control" id="email"></div><div class="col-md-6"><label>Dirección</label><input type="text" class="form-control" id="direccion"></div><div class="col-md-3"><label>Cobertura %</label><input type="number" step="0.01" class="form-control" id="porcentaje_cobertura_default" value="80"></div><div class="col-md-3"><label>Activo</label><select class="form-select" id="activo"><option value="1">Activo</option><option value="0">Inactivo</option></select></div><div class="col-md-12"><label>Observaciones</label><textarea class="form-control" id="observaciones" rows="2"></textarea></div></div></form></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary" onclick="guardarAseguradora()">Guardar</button></div></div></div></div>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
const BASE_URL = '<?php echo $base_url; ?>';
function aplicarFiltros(){ let url=BASE_URL+'/frontend/menuprincipal.php?mod=seguros_medicos&busqueda='+encodeURIComponent(document.getElementById('busqueda').value)+'&activo='+document.getElementById('filtroActivo').value; window.location.href=url; }
function limpiarFiltros(){ window.location.href=BASE_URL+'/frontend/menuprincipal.php?mod=seguros_medicos'; }
function resetFormAseguradora(){ document.getElementById('formAseguradora').reset(); document.getElementById('id_aseguradora').value=''; }
function editarAseguradora(id){ fetch(BASE_URL+'/backend/administracion/get_aseguradora.php?id='+id).then(r=>r.json()).then(data=>{ if(data.success){ document.getElementById('id_aseguradora').value=data.id_aseguradora; document.getElementById('codigo').value=data.codigo; document.getElementById('nombre').value=data.nombre; document.getElementById('rnc').value=data.rnc; document.getElementById('telefono').value=data.telefono; document.getElementById('email').value=data.email; document.getElementById('direccion').value=data.direccion; document.getElementById('porcentaje_cobertura_default').value=data.porcentaje_cobertura_default; document.getElementById('activo').value=data.activo?'1':'0'; document.getElementById('observaciones').value=data.observaciones; new bootstrap.Modal(document.getElementById('modalAseguradora')).show(); } else Swal.fire('Error','No se pudo cargar','error'); }).catch(()=>Swal.fire('Error','Error de conexión','error')); }
function guardarAseguradora(){ let data={ id_aseguradora: document.getElementById('id_aseguradora').value, codigo: document.getElementById('codigo').value, nombre: document.getElementById('nombre').value, rnc: document.getElementById('rnc').value, telefono: document.getElementById('telefono').value, email: document.getElementById('email').value, direccion: document.getElementById('direccion').value, porcentaje_cobertura_default: parseFloat(document.getElementById('porcentaje_cobertura_default').value), activo: document.getElementById('activo').value==='1', observaciones: document.getElementById('observaciones').value }; fetch(BASE_URL+'/backend/administracion/guardar_aseguradora.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(r=>r.json()).then(res=>{ if(res.success){ Swal.fire('Éxito','Aseguradora guardada','success').then(()=>location.reload()); } else Swal.fire('Error',res.message,'error'); }).catch(()=>Swal.fire('Error','Error de conexión','error')); }
function toggleEstadoAseguradora(id, activar){ Swal.fire({title:'Confirmar',text:`¿${activar?'Activar':'Desactivar'} aseguradora?`,icon:'question',showCancelButton:true}).then(result=>{ if(result.isConfirmed){ fetch(BASE_URL+'/backend/administracion/cambiar_estado_aseguradora.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id_aseguradora:id,activo:activar})}).then(r=>r.json()).then(res=>{ if(res.success) Swal.fire('Éxito','Estado cambiado','success').then(()=>location.reload()); else Swal.fire('Error',res.message,'error'); }); } }); }
</script>